baseURL = "https://gifted-mirzakhani-ffbf7a.netlify.app/"
languageCode = "en-us"
theme = "hyde"
title = "TECH New Home"
[params]
disqusShortname = ""
googleAnalytics = ""
layoutReverse = false
theme = "hyde"
themeColor = ""
